# Generated by Django 3.1.7 on 2021-04-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evcontrol', '0002_auto_20210403_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evcontrol.event'),
            preserve_default=False,
        ),
    ]
